/**
 * Node-side client for the local embedding daemon (python/embed_server.py)
 * behind "Naheliegendes" — see the Spinnennetz Stufe-1 plan's "Einbetten"
 * section. The daemon is a long-lived, pm2-managed process (unlike the other
 * python/ helpers, which spawn a fresh subprocess per call — see
 * python/embed_server.py's own docstring for why that pattern doesn't fit
 * here), so this is a plain HTTP client to 127.0.0.1, not a spawn wrapper
 * like lib/pythonTools.ts.
 *
 * Every failure mode (daemon down, timeout, bad response) throws
 * EmbeddingError — callers in lib/knowledgeUnits.ts catch this and degrade
 * gracefully (a nugget just doesn't show up as "related" yet) rather than
 * ever breaking a save.
 */

/** The embedding model id — stored on every KnowledgeUnit row so a model swap can be detected and filtered at query time. */
export const EMBED_MODEL = process.env.EMBED_MODEL?.trim() || 'intfloat/multilingual-e5-small'

/** intfloat/multilingual-e5-small's output size — matches KnowledgeUnit.dim's default. */
export const EMBED_DIM = 384

const EMBED_DAEMON_PORT = process.env.EMBED_DAEMON_PORT?.trim() || '8801'
const EMBED_DAEMON_URL = `http://127.0.0.1:${EMBED_DAEMON_PORT}`

export class EmbeddingError extends Error {
  constructor(message: string, readonly detail?: string) {
    super(message)
    this.name = 'EmbeddingError'
  }
}

/**
 * "passage" = indexed content (paragraphs/marks/comments, embedded once at
 * save time); "query" = the ephemeral text sampled at the current reading
 * position (embedded once per /api/nearby call). e5's asymmetric-retrieval
 * training expects this distinction — see python/embed_server.py's PREFIXES.
 */
export type EmbedMode = 'query' | 'passage'

/** Embeds a batch of texts in ONE request, so a multi-chunk reindex pays one round trip, not one per chunk. */
export async function embedTexts(texts: string[], mode: EmbedMode): Promise<Float32Array[]> {
  if (texts.length === 0) return []

  let response: Response
  try {
    response = await fetch(`${EMBED_DAEMON_URL}/embed`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ texts, mode }),
      signal: AbortSignal.timeout(30_000),
    })
  } catch (error) {
    throw new EmbeddingError(
      'Embedding-Dienst nicht erreichbar.',
      error instanceof Error ? error.message : String(error),
    )
  }

  if (!response.ok) {
    let detail = `HTTP ${response.status}`
    try {
      const body = (await response.json()) as { error?: unknown }
      if (typeof body.error === 'string') detail = body.error
    } catch { /* body wasn't JSON — keep the status code as the detail */ }
    throw new EmbeddingError('Embedding-Dienst hat einen Fehler gemeldet.', detail)
  }

  const data = (await response.json()) as { vectors?: unknown }
  if (!Array.isArray(data.vectors)) {
    throw new EmbeddingError('Unerwartete Antwort des Embedding-Diensts.')
  }
  return data.vectors.map(v => new Float32Array(v as number[]))
}

/** Health check for GET /api/tools/status — never throws, just reports reachability. */
export async function embedDaemonHealth(): Promise<{ ok: boolean; model?: string; dim?: number; error?: string }> {
  try {
    const response = await fetch(`${EMBED_DAEMON_URL}/health`, { signal: AbortSignal.timeout(3_000) })
    if (!response.ok) return { ok: false, error: `HTTP ${response.status}` }
    const data = (await response.json()) as { ok?: boolean; model?: string; dim?: number }
    return { ok: data.ok === true, model: data.model, dim: data.dim }
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) }
  }
}

/**
 * Packs a vector into a compact byte array for storage in
 * KnowledgeUnit.embedding (Bytes) — ~6-8x smaller than a JSON float array,
 * no parse cost on load. Prisma's `Bytes` type is `Uint8Array<ArrayBuffer>`
 * (`ReturnType<Uint8Array['slice']>`, not `Buffer`) — `.slice()` with no
 * args both copies and produces exactly that type, which a `Buffer` (typed
 * `Buffer<ArrayBufferLike>`) doesn't structurally satisfy.
 */
export function packVector(v: Float32Array): Uint8Array<ArrayBuffer> {
  const view = new Uint8Array(v.buffer, v.byteOffset, v.byteLength)
  // A view constructed FROM v.buffer infers Uint8Array<ArrayBufferLike>
  // (v.buffer is typed ArrayBufferLike) — copy into an explicitly
  // ArrayBuffer-backed Uint8Array, which is what Prisma's generated Bytes
  // field type (Uint8Array<ArrayBuffer>) requires.
  // The plain numeric-length overload allocates a real ArrayBuffer at
  // runtime; only its TS type defaults to the generic ArrayBufferLike
  // parameter, so this narrows a true invariant rather than lying about one.
  const out = new Uint8Array(view.byteLength) as Uint8Array<ArrayBuffer>
  out.set(view)
  return out
}

/** Unpacks a Bytes column value (a Uint8Array/Buffer) back into a Float32Array — the inverse of packVector. */
export function unpackVector(b: Uint8Array): Float32Array {
  const buf = Buffer.isBuffer(b) ? b : Buffer.from(b.buffer, b.byteOffset, b.byteLength)
  return new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4)
}
